paths:
  nfe_input_folder: "data/"
  master_data_file: "data/MART-Ficha-tecnica-2024-05-22.xlsx"
  output_folder: "output/"
  log_folder: "logs/"
  synonym_cache_file: "data/synonyms.json"

pricing:
  strategy: "markup_fixo"
  markup_factor: 2.2

csv_output:
  filename_prefix: "importacao_produtos_"
  columns:
    - "Handle"
    - "Title"
    - "Vendor"
    - "Product Type"
    - "SKU"
    - "Barcode"
    - "Status"
    - "Published"
    - "Tags"
    - "Price"
    - "Compare At Price"
    - "Cost per item"
    - "Inventory Qty"
    - "Weight"
    - "Image Src"

metafields:
  namespace: "custom"
  keys:
    unidade: "unidade"
    ncm: "ncm"
    cest: "cest"
    cfop: "cfop"
    icms: "icms"
    composicao: "composicao"
