paths:
  nfe_input_folder: "data/"
  master_data_file: "example_docs/MART-Ficha-tecnica-Biblioteca-Virtual-08-08-2025.xlsx"
  output_folder: "output/super/"
  log_folder: "logs/super/"
  synonym_cache_file: "data/synonyms.json"

pricing:
  strategy: "markup_fixo"
  markup_factor: 2.2

csv_output:
  filename_prefix: "importacao_produtos_super_"
  columns:
    - "Handle"
    - "Title"
    - "Body (HTML)"
    - "Vendor"
    - "Tags"
    - "Published"
    - "Option1 Name"
    - "Option1 Value"
    - "Option2 Name"
    - "Option2 Value"
    - "Option3 Name"
    - "Option3 Value"
    - "Variant SKU"
    - "Variant Price"
    - "Variant Compare At Price"
    - "Variant Inventory Qty"
    - "Variant Weight"
    - "Variant Weight Unit"
    - "Variant Requires Shipping"
    - "Image Src"
    - "Variant Barcode"
    - "Variant Grams"
    - "Variant Inventory Tracker"
    - "Variant Inventory Policy"
    - "Variant Fulfillment Service"
    - "product.metafields.custom.unidade"
    - "product.metafields.custom.catalogo"
    - "product.metafields.custom.dimensoes_do_produto"
    - "product.metafields.custom.composicao"
    - "product.metafields.custom.capacidade"
    - "product.metafields.custom.modo_de_uso"
    - "product.metafields.custom.icms"
    - "product.metafields.custom.ncm"
    - "product.metafields.custom.pis"
    - "product.metafields.custom.ipi"
    - "product.metafields.custom.cofins"
    - "product.metafields.custom.componente_de_kit"
    - "product.metafields.custom.resistencia_a_agua"
    - "Variant Taxable"
    - "Cost per item"
    - "Image Position"
    - "Variant Image"
    - "Product Category"
    - "Type"
    - "Collection"
    - "Status"

metafields:
  namespace: "custom"
  keys:
    unidade: "unidade"
    catalogo: "catalogo"
    dimensoes_do_produto: "dimensoes_do_produto"
    composicao: "composicao"
    capacidade: "capacidade"
    modo_de_uso: "modo_de_uso"
    icms: "icms"
    ncm: "ncm"
    pis: "pis"
    ipi: "ipi"
    cofins: "cofins"
    componente_de_kit: "componente_de_kit"
    resistencia_a_agua: "resistencia_a_agua"
  dynamic_mapping:
    enabled: true
    map:
      unidade: "unit"
      catalogo: "catalogo"
      dimensoes_do_produto: "medidas_s_emb"
      capacidade: "capacidade__ml_ou_peso_suportado"
      ncm: "ncm"
      modo_de_uso: "features"

variants:
  enabled: true
  option1:
    name: "Color"
    column: "cor"
  option2:
    name: "Tamanho"
    column: "tamanho"

weights:
  dynamic_unit: true
  column: "peso"
  unit_column: "un_peso"
  default_unit: "kg"

